# Generated by Django 4.2.8 on 2023-12-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yourdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField()),
                ('intensity', models.IntegerField()),
                ('sector', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('insight', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('region', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('impact', models.CharField(max_length=255)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=255)),
                ('relevance', models.IntegerField()),
                ('pestle', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('likelihood', models.IntegerField()),
            ],
        ),
    ]
