# Generated by Django 4.2.8 on 2023-12-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_yourdata_added_alter_yourdata_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourdata',
            name='end_year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='yourdata',
            name='start_year',
            field=models.CharField(max_length=100),
        ),
    ]
