# Generated by Django 4.2.8 on 2023-12-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_yourdata_end_year_alter_yourdata_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourdata',
            name='intensity',
            field=models.CharField(max_length=100),
        ),
    ]
