# Generated by Django 4.2.8 on 2023-12-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_yourdata_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourdata',
            name='likelihood',
            field=models.CharField(max_length=100),
        ),
    ]
