# Generated by Django 4.2.8 on 2023-12-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_yourdata_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourdata',
            name='relevance',
            field=models.CharField(max_length=100),
        ),
    ]
