# Generated by Django 4.2.8 on 2023-12-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_yourdata_relevance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourdata',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yourdata',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
